### PR TITLE
Patchit

### PR DESCRIPTION
**Pull request by dmennis**
Change #1:
> Updated Dockerfile in the Keycloak script and deploy folders with a hard-coded known supported version of Keycloak services to be deployed. Changed from default of no version preference to version 21.0.1. Prior to this change, the Keycloak deployed version was 22.0.3 as of Oct 4. After this change, the deployment script will deploy version 21.0.1 of Keycloak as we know this is compatible with this version the passkey-workshop.

Change #2:
> Updated the version of Keycloak service to static version 21.1.2 to satisfy five dependabot issues
https://github.com/YubicoLabs/passkey-workshop/security/dependabot/13 (Moderate)
https://github.com/YubicoLabs/passkey-workshop/security/dependabot/14 (Moderate)
https://github.com/YubicoLabs/passkey-workshop/security/dependabot/15 (Critical)
https://github.com/YubicoLabs/passkey-workshop/security/dependabot/16 (High)
https://github.com/YubicoLabs/passkey-workshop/security/dependabot/23 (Moderate)

### CODE REVIEW

**Comment by dmennis** [comment]
Made two minor changes to the Keycloak deployment versions to satisfy compatibility and resolve several dependabot issues.

**Comment by joostd** [comment]
Are there compatibility issues with 22.0.3 that prevent us from upgrading to that version?

**Review by joostd — APPROVED** [review]

**Comment by dmennis** [comment]
> Are there compatibility issues with 22.0.3 that prevent us from upgrading to that version?

Yes. 22.0.3 results in an uncaught server exception when registering a new user. Looks like an issue with token format?!

Here's a snippet of the Keycloak logs from v.22.0.3
2023-10-06 12:10:10 passkey-keycloak  | 2023-10-06 19:10:10,429 WARN  [org.keycloak.events] (executor-thread-1) type=USER_INFO_REQUEST_ERROR, realmId=0d3fb808-461a-4ccb-ac95-38ed34a22627, clientId=null, userId=null, ipAddress=192.168.65.1, error=invalid_token, auth_method=validate_access_token
2023-10-06 12:10:10 passkey-keycloak  | 2023-10-06 19:10:10,442 WARN  [org.keycloak.events] (executor-thread-1) type=REFRESH_TOKEN_ERROR, realmId=0d3fb808-461a-4ccb-ac95-38ed34a22627, clientId=passkeyClient, userId=null, ipAddress=192.168.65.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
2023-10-06 12:10:27 passkey-keycloak  | 2023-10-06 19:10:27,791 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NoSuchMethodError: 'javax.ws.rs.core.MultivaluedMap org.keycloak.http.HttpRequest.getDecodedFormParameters()'
2023-10-06 12:10:27 passkey-keycloak  |         at com.yubicolabs.PasskeyAuthenticator.PasskeyRegistrationAuthenticator.authenticate(PasskeyRegistrationAuthenticator.java:46)

**Comment by csalas-yubico** [comment]
No issues found; tested on MacOS against Chrome, Safari, and Firefox; Approved

**Review by csalas-yubico — APPROVED** [review]

**Pull request merged**
